# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Vault_ClientFacingApp' do

pod 'Devise', '~> 1.0.0'
pod 'AFNetworking', '~> 2.5'
pod ‘KAProgessLabel’

end

target 'Vault_ClientFacingAppTests' do

end

